name: 'multi-approvers'

on:
  pull_request_target:
    types:
      - 'opened'
      - 'edited'
      - 'reopened'
      - 'synchronize'
      - 'ready_for_review'
      - 'review_requested'
      - 'review_request_removed'
  pull_request_review:
    types:
      - 'submitted'
      - 'dismissed'

permissions:
  actions: 'write'
  contents: 'read'
  id-token: 'write'
  pull-requests: 'read'

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  multi-approvers:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Multi-approvers'
        uses: 'abcxyz/actions/.github/actions/multi-approvers@d94796fb79fd38c346e223cebdd615fddfb03d0e'
        with:
          team: 'multi-approvers'
          token: '${{ secrets.MULTI_APPROVERS_TOKEN }}'
          user-id-allowlist: '25180681,7163701,7163701,122572305,78513119,27347476,70984784,44816363'
          # username to ID mapping (https://api.github.com/users{username}):
          #   renovate-bot: 25180681
          #   release-please[bot]: 7163701
          #   cloud-java-bot: 122572305
          #   gcf-owl-bot[bot]: 78513119
          #   dependabot[bot]: 27347476
          #   yoshi-code-bot: 70984784
          #   yoshi-automation: 44816363