name: 'multi-approvers'

on:
  pull_request_target:
    types:
      - 'opened'
      - 'edited'
      - 'reopened'
      - 'synchronize'
      - 'ready_for_review'
      - 'review_requested'
      - 'review_request_removed'
  pull_request_review:
    types:
      - 'submitted'
      - 'dismissed'

permissions:
  actions: 'write'
  contents: 'read'
  id-token: 'write'
  pull-requests: 'read'

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  multi-approvers:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Multi-approvers'
        uses: 'abcxyz/actions/.github/actions/multi-approvers@6994d739e27f8485dcafad56c0f5dfe506b481a8'
        with:
          team: 'multi-approvers'
          token: '${{ secrets.MULTI_APPROVERS_TOKEN }}'
          user-id-allowlist: 'renovate-bot,release-please[bot],cloud-java-bot,gcf-owl-bot[bot],dependabot[bot],yoshi-code-bot,yoshi-automation'
